package com.vj.bookweb_service.book;

import jakarta.persistence.*;

    @Entity
    @Table(name = "books")
    public class Book {

        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        private Integer id;

        private String title;

        private String author;

        @Column(name = "publication_year")
        private Integer publicationYear;

        private String category;

        private boolean available;

        // Empty constructor – JPA needs this to create objects from the database
        public Book() {
        }

        // Constructor for creating new books (id is generated by the database)
        public Book(String title, String author, Integer publicationYear, String category, boolean available) {
            this.title = title;
            this.author = author;
            this.publicationYear = publicationYear;
            this.category = category;
            this.available = available;
        }

        public Integer getId() {
            return id;
        }

        public void setId(Integer id) {
            this.id = id;
        }

        public String getTitle() {
            return title;
        }

        public void setTitle(String title) {
            this.title = title;
        }

        public String getAuthor() {
            return author;
        }

        public void setAuthor(String author) {
            this.author = author;
        }

        public Integer getPublicationYear() {
            return publicationYear;
        }

        public void setPublicationYear(Integer publicationYear) {
            this.publicationYear = publicationYear;
        }

        public String getCategory() {
            return category;
        }

        public void setCategory(String category) {
            this.category = category;
        }

        public boolean isAvailable() {
            return available;
        }

        public void setAvailable(boolean available) {
            this.available = available;
        }

        @Override
        public String toString() {
            return "Book{" +
                    "id=" + id +
                    ", title='" + title + '\'' +
                    ", author='" + author + '\'' +
                    ", publicationYear=" + publicationYear +
                    ", category='" + category + '\'' +
                    ", available=" + available +
                    '}';
        }
    }

